"""Add index to category, is_free, and difficulty

Revision ID: 89a8fee4b816
Revises: 0160d3cdb3d7
Create Date: 2026-06-02 19:38:32.234808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a8fee4b816'
down_revision: Union[str, None] = '0160d3cdb3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_opportunities_category'), 'opportunities', ['category'], unique=False)
    op.create_index(op.f('ix_opportunities_difficulty'), 'opportunities', ['difficulty'], unique=False)
    op.create_index(op.f('ix_opportunities_is_free'), 'opportunities', ['is_free'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_is_free'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_difficulty'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_category'), table_name='opportunities')
    # ### end Alembic commands ###
